### ISSUE TITLE
iOS16(A16) GPU Counters error

### ISSUE THREAD

**Issue by FewL** [YueChen-C/py-ios-device#123]
**Smartphone:**
 - Device: iPhone14 pro
 - OS: iOS16.0.2
 - Pyidevice Version 2.3.2

**Bug Description**
When I use command `pyidevice instruments gpu_counters`, an error occurs:
```
2023-09-07 22:07:56 [INFO] [LockDown] lockdown.py[line:73] Connecting Device 0000XXXX-00XXXXXX0XXXX0XX 
2023-09-07 22:07:56 [INFO] [Instrument] base.py[line:408] Wait for gup counters data ...
2023-09-07 22:07:59 [ERROR] [Instrument] dvt.py[line:250] TraceData.__init__() takes from 6 to 7 positional arguments but 8 were given
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ios_device/servers/dvt.py", line 243, in _receiver
    self._undefined_callback(dtx)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ios_device/cli/instruments.py", line 443, in dropped_message
    js_env.dump_trace(TraceData(*res.selector))
                      ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TraceData.__init__() takes from 6 to 7 positional arguments but 8 were given
```

p.s.
`gup` is a typo ;)

**Comment by YueChen-C** [comment]
thinks ~
