### ISSUE TITLE
Get issue when execute command  pyidevice crash list --udid

### ISSUE THREAD

**Issue by Shakezila** [YueChen-C/py-ios-device#132]
os monterey: 12.7.3
python version: 3.11
device os version: 14.8.1
py-ios-device version: 2.4.10
```
Traceback (most recent call last):
  File "/usr/local/bin/pyidevice", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/local/lib/python3.11/site-packages/ios_device/main.py", line 10, in cli
    cli_commands()
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ios_device/cli/mobile.py", line 58, in crash_list
    crash_server = CrashLogService(udid=udid, network=network, logger=log)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ios_device/servers/crash_log.py", line 16, in __init__
    self.crash_server = AFCCrashLog(lockdown=self.lockdown)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ios_device/servers/afc.py", line 564, in __init__
    SERVICE_NAME = self.RSD_SERVICE_NAME if isinstance(self.lockdown,
                                                       ^^^^^^^^^^^^^
AttributeError: 'AFCCrashLog' object has no attribute 'lockdown'
```

**Comment by Shakezila** [comment]
fixed by installing older version pip install py-ios-device==2.3.2
