### ISSUE TITLE
instruments networking crash on iOS 17.5.1

### ISSUE THREAD

**Issue by Alex15190** [YueChen-C/py-ios-device#152]
**Smartphone:**
 - Device: iPhone 14 Pro
 - iOS 17.5.1
 - py-ios-device-2.4.15

**Describe the bug**
After launching of monitor test I received this crash (dev mode enabled)

cmd```
idevice instruments networking
2024-08-21 16:52:56 [INFO] [LockDown] lockdown.py[line:73] Connecting Device IPHONE-UDID
2024-08-21 16:52:56 [INFO] [LockDown] lockdown.py[line:261] try `pyidevice enable_developer_mode`
2024-08-21 16:52:56 [INFO] [LockDown] lockdown.py[line:73] Connecting Device IPHONE-UDID
2024-08-21 16:52:56 [INFO] [LockDown] lockdown.py[line:302] ProductVersion: 17.5.1
2024-08-21 16:52:56 [INFO] [LockDown] lockdown.py[line:317] Download https://github.com/JinjunHan/iOSDeviceSupport/raw/master/iOSDeviceSupport/17.5.zip -> /Users/USER/.py_ios_device/device-support/17.5.zip
2024-08-21 16:52:56 [INFO] [LockDown] lockdown.py[line:280] Download https://raw.githubusercontent.com/filsv/iPhoneOSDeviceSupport/master/17.5.zip -> /Users/USER/.py_ios_device/device-support/17.5.zip
2024-08-21 16:52:57 [INFO] [LockDown] lockdown.py[line:280] Download https://github.com/JinjunHan/iOSDeviceSupport/raw/master/iOSDeviceSupport/17.5.zip -> /Users/USER/.py_ios_device/device-support/17.5.zip
Traceback (most recent call last):
  File "/Users/USER/Library/Python/3.9/lib/python/site-packages/ios_device/util/lockdown.py", line 350, in start_service
    return self._start_service(name, escrow_bag)
  File "/Users/USER/Library/Python/3.9/lib/python/site-packages/ios_device/util/lockdown.py", line 262, in _start_service
    raise StartServiceError(f'Unable to start service={name!r} - {error}')
ios_device.util.exceptions.StartServiceError: Unable to start service='com.apple.instruments.remoteserver.DVTSecureSocketProxy' - InvalidService

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/USER/Library/Python/3.9/lib/python/site-packages/ios_device/util/lockdown.py", line 319, in _request_developer_image_dir
    self._urlretrieve(mirror_url, image_zip_path)
  File "/Users/USER/Library/Python/3.9/lib/python/site-packages/ios_device/util/lockdown.py", line 285, in _urlretrieve
    r.raise_for_status()
  File "/Users/USER/Library/Python/3.9/lib/python/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/filsv/iPhoneOSDeviceSupport/master/17.5.zip

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/USER/Library/Python/3.9/bin/pyidevice", line 8, in <module>
    sys.exit(cli())
  File "/Users/USER/Library/Python/3.9/lib/python/site-packages/ios_device/main.py", line 10, in cli
    cli_commands()
  File "/Users/USER/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/USER/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/USER/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/USER/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/USER/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/USER/Library/Python/3.9/lib/python/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/USER/Library/Python/3.9/lib/python/site-packages/ios_device/cli/instruments.py", line 153, in cmd_networking
    rpc.networking(_callback)
  File "/Users/USER/Library/Python/3.9/lib/python/site-packages/ios_device/cli/base.py", line 344, in networking
    self.instruments.register_channel_callback(InstrumentsService.Networking, callback)
  File "/Users/USER/Library/Python/3.9/lib/python/site-packages/ios_device/cli/base.py", line 181, in instruments
    self.instruments_rcp = InstrumentServer(lockdown=self.lockdown).init()
  File "/Users/USER/Library/Python/3.9/lib/python/site-packages/ios_device/servers/Instrument.py", line 20, in init
    cli = self.lockdown.start_service("com.apple.instruments.remoteserver.DVTSecureSocketProxy")
  File "/Users/USER/Library/Python/3.9/lib/python/site-packages/ios_device/util/lockdown.py", line 352, in start_service
    self.mount_developer_image()
  File "/Users/USER/Library/Python/3.9/lib/python/site-packages/ios_device/util/lockdown.py", line 342, in mount_developer_image
    with self._request_developer_image_dir() as _dir:  # , signature_path:
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "/Users/USER/Library/Python/3.9/lib/python/site-packages/ios_device/util/lockdown.py", line 323, in _request_developer_image_dir
    self._urlretrieve(origin_url, image_zip_path)
  File "/Users/USER/Library/Python/3.9/lib/python/site-packages/ios_device/util/lockdown.py", line 285, in _urlretrieve
    r.raise_for_status()
  File "/Users/USER/Library/Python/3.9/lib/python/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://github.com/JinjunHan/iOSDeviceSupport/raw/master/iOSDeviceSupport/17.5.zip

```

**Comment by YueChen-C** [comment]
https://github.com/YueChen-C/py-ios-device#support-ios-17-command-line-is-not-supported-

Please carefully review the readme.md

**Comment by Alex15190** [comment]
Got it! Thanks!
