### ISSUE TITLE
访问 plist 报错Permission denied

### ISSUE THREAD

**Issue by Huang-Jacky** [YueChen-C/py-ios-device#16]
2021-05-27 13:37:47 [INFO] [USBMux] usbmux.py[line:139] Connecting Device serial:00008030-00015C483630802E, ConnectionType:USB
Traceback (most recent call last):
  File "/Library/Python/3.8/site-packages/ios_device/util/lockdown.py", line 95, in _get_pair_record
    if itunes_lockdown_path.exists():
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/pathlib.py", line 1383, in exists
    self.stat()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/pathlib.py", line 1189, in stat
    return self._accessor.stat(self)
PermissionError: [Errno 13] Permission denied: '/var/db/lockdown/00008030-00015C483630802E.plist'

**Comment by YueChen-C** [comment]
这段代码应有异常捕获，会走其他逻辑才对，你的是最新代码吗？
```
        try:  # 如果没有 lockdown 权限，则使用自有缓存证书配对，建议开启 lockdown 权限
            if itunes_lockdown_path.exists():
                log.debug(f'Using iTunes pair record: {itunes_lockdown_path}')
                with itunes_lockdown_path.open('rb') as f:
                    return plistlib.load(f)
        except Exception as E:
```
