### ISSUE TITLE
getting error while running launchapp

### ISSUE THREAD

**Issue by bikee1235** [YueChen-C/py-ios-device#24]
sudo python3 launchapp.py d2ff3799d220fdsfds1f98ec3bdcb1a5b6e2e08 net.openvpn.connect.app 
Number of arguments: 3 arguments.
d2ff3799d220fdsfds1f98ec3bdcb1a5b6e2e08
Argument List: ['launchapp.py', 'd2ff3799d220fdsfds1f98ec3bdcb1a5b6e2e08', 'net.openvpn.connect.app']
Traceback (most recent call last):
  File "/Users/radmin/py-ios-devicev1/demo/instrument_demo/launchapp.py", line 5, in <module>
    from ios_device.servers.Instrument import InstrumentServer
  File "/Users/radmin/py-ios-devicev1/ios_device/servers/Instrument.py", line 7, in <module>
    from ..util.lockdown import LockdownClient
  File "/Users/radmin/py-ios-devicev1/ios_device/util/lockdown.py", line 24, in <module>
    from .utils import DictAttrProperty, cached_property
  File "/Users/radmin/py-ios-devicev1/ios_device/util/utils.py", line 4, in <module>
    from ios_device.util.service_info import MyServiceInfo
  File "/Users/radmin/py-ios-devicev1/ios_device/util/service_info.py", line 8, in <module>
    from zeroconf import ServiceInfo, _TYPE_A, _TYPE_AAAA, DNSAddress, _TYPE_SRV, DNSService, _CLASS_IN, \
ImportError: cannot import name '_TYPE_A' from 'zeroconf' (/usr/local/lib/python3.9/site-packages/zeroconf/__init__.py)
Mac-book:instrument_demo radmin$ 

getting this while running launchapp.py

I am trying to run from the source  

 modified in such a way that can read udid and app id from cmd line 

if __name__ == '__main__':
    rpc =  rpc = InstrumentServer(udid=sys.argv[1]).init()
    _launch_app(rpc, sys.argv[2])
    rpc.stop()

**Comment by YueChen-C** [comment]
Zeroconf lib is no longer used in the latest code。This error may be a zeroconf version difference
