### ISSUE TITLE
运行 pyidevice instruments runningProcesses --format=json 命令失败

### ISSUE THREAD

**Issue by wgywgy** [YueChen-C/py-ios-device#33]
你好，我在运行 pyidevice instruments runningProcesses --format=json 命令后，有报错信息
运行日志：
➜  airTest pyidevice instruments runningProcesses --format=json
2021-08-13 11:11:15 [INFO] [LockDown] lockdown.py[line:71] Connecting Device 00008020-000E744A11A2xxxx
2021-08-13 11:11:15 [INFO] [Instrument] Instrument.py[line:22] InstrumentServer init ...
2021-08-13 11:11:15 [INFO] [LockDown] lockdown.py[line:384] save path :/Users/guanyu/.cache/pymobiledevice/00008020-000E744A11A2xxxx.pem
2021-08-13 11:11:15 [WARNING] [Instrument] dvt.py[line:245] socket connection close
Traceback (most recent call last):
  File "/usr/local/bin/pyidevice", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/ios_device/main.py", line 15, in cli
    cli_commands()
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/ios_device/cli/instruments.py", line 43, in cmd_running_processes
    processes = rpc.device_info.runningProcesses()
  File "/usr/local/lib/python3.9/site-packages/ios_device/cli/base.py", line 34, in runningProcesses
    parsed = self.rpc.call(InstrumentsService.DeviceInfo, "runningProcesses").selector
AttributeError: 'bool' object has no attribute 'call'

**Comment by YueChen-C** [comment]
InstrumentServer init 初始化失败了，用最新版在环境变量加 debug=1 运行看看
或者下载源码debug 看看报啥错了

**Comment by PrideChung** [comment]
可能跟iOS 15系统有关，我在iOS 13的测试机上是正常的，看debug信息似乎是没能成功建立tcp连接？

2021-09-26 18:08:58 [DEBUG] [ios_device.util.plist_service] plist_service.py[line:34] Connecting to device: 6e7dd11ba22ee2ce960a4ccaafa6ae30b2ade47d
2021-09-26 18:08:58 [DEBUG] [USBMux] usbmux.py[line:327] 发送 Plist: {'DeviceID': 23, 'PortNumber': 13281, 'ClientVersionString': 'qt4i-usbmuxd', 'MessageType': 'Connect', 'ProgName': 'tcprelay'}
2021-09-26 18:08:58 [DEBUG] [USBMux] usbmux.py[line:288] 发送 Plist byte: b'\xca\x01\x00\x00\x01\x00\x00\x00\x08\x00\x00\x00\x01\x00\x00\x00<?xml version="1.0" encoding="UTF-8"?>\n<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n<plist version="1.0">\n<dict>\n\t<key>ClientVersionString</key>\n\t<string>qt4i-usbmuxd</string>\n\t<key>DeviceID</key>\n\t<integer>23</integer>\n\t<key>MessageType</key>\n\t<string>Connect</string>\n\t<key>PortNumber</key>\n\t<integer>13281</integer>\n\t<key>ProgName</key>\n\t<string>tcprelay</string>\n</dict>\n</plist>\n'
2021-09-26 18:08:58 [DEBUG] [USBMux] usbmux.py[line:333] 接收 Plist byte: b'<?xml version="1.0" encoding="UTF-8"?>\n<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n<plist version="1.0">\n<dict>\n\t<key>MessageType</key>\n\t<string>Result</string>\n\t<key>Number</key>\n\t<integer>0</integer>\n</dict>\n</plist>\n'
2021-09-26 18:08:58 [DEBUG] [USBMux] usbmux.py[line:337] 接收 Plist: {'MessageType': 'Result', 'Number': 0}
2021-09-26 18:08:58 [WARNING] [Instrument] dvt.py[line:245] socket connection close

**Comment by YueChen-C** [comment]
@PrideChung  重启一下吧，重启后会从新激活开发者模式，看看是否正常

**Comment by YueChen-C** [comment]
@PrideChung  重启一下吧，重启后会从新激活开发者模式，看看是否正常
