### ISSUE TITLE
Unable to start service='com.apple.instruments.remoteserver.DVTSecureSocketProxy' - InvalidService

### ISSUE THREAD

**Issue by popiggy** [YueChen-C/py-ios-device#51]
Hello @YueChen-C ,

When I launch the command "**pyidevice instruments monitor**", I get the following error, could you please give some help?
My environment : Windows 10 / iPhone 12 / iOS 15.0.2

2021-11-24 15:44:33 [INFO] [LockDown] lockdown.py[line:71] Connecting Device 00008101-XXXXX
2021-11-24 15:44:33 [INFO] [Instrument] Instrument.py[line:22] InstrumentServer init ...
2021-11-24 15:44:33 [INFO] [LockDown] lockdown.py[line:377] save path :C:\Users\xxxx\.cache\pymobiledevice\00008101-XXXXX.pem
2021-11-24 15:44:33 [INFO] [LockDown] lockdown.py[line:71] Connecting Device 00008101-XXXXX
_2021-11-24 15:44:33 [INFO] [LockDown] lockdown.py[line:294] ProductVersion: 15.0.2
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\ios_device\util\lockdown.py", line 342, in start_service
    return self._start_service(name, escrow_bag)
  **File "C:\Python39\lib\site-packages\ios_device\util\lockdown.py", line 258, in start_service
    raise StartServiceError(f'Unable to start service={name!r} - {error}')
ios_device.util.exceptions.StartServiceError: Unable to start service='com.apple.instruments.remoteserver.DVTSecureSocketProxy' - InvalidService**

**Comment by YueChen-C** [comment]
Try to restart the device, and then execute the command will re-push DeveloperImage

**Comment by popiggy** [comment]
hello, same thing after restarting the phone...here's the exception occuring after the previous error message : 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python39\Scripts\pyidevice.exe\__main__.py", line 7, in <module>
  File "C:\Python39\lib\site-packages\ios_device\main.py", line 15, in cli
    cli_commands()
  File "C:\Python39\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Python39\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Python39\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Python39\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Python39\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Python39\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Python39\lib\site-packages\ios_device\cli\instruments.py", line 267, in cmd_monitor
    rpc.sysmontap(on_callback_message)
  File "C:\Python39\lib\site-packages\ios_device\cli\base.py", line 251, in sysmontap
    self.system_attributes = self.system_attributes or list(self.device_info.sysmonSystemAttributes())
  File "C:\Python39\lib\site-packages\ios_device\cli\base.py", line 190, in device_info
    rpc = self.instruments
  File "C:\Python39\lib\site-packages\ios_device\cli\base.py", line 178, in instruments
    self.instruments_rcp = InstrumentServer(lockdown=self.lock_down).init()
  File "C:\Python39\lib\site-packages\ios_device\servers\Instrument.py", line 32, in init
    raise E
  File "C:\Python39\lib\site-packages\ios_device\servers\Instrument.py", line 26, in init
    self._cli = self.lockdown.start_service("com.apple.instruments.remoteserver.DVTSecureSocketProxy")
  File "C:\Python39\lib\site-packages\ios_device\util\lockdown.py", line 344, in start_service
    self.mount_developer_image()
  File "C:\Python39\lib\site-packages\ios_device\util\lockdown.py", line 334, in mount_developer_image
    with self._request_developer_image_dir() as _dir:  # , signature_path:
  File "C:\Python39\lib\contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "C:\Python39\lib\site-packages\ios_device\util\lockdown.py", line 318, in _request_developer_image_dir
    zf = zipfile.ZipFile(image_zip_path)
  File "C:\Python39\lib\zipfile.py", line 1257, in __init__
    self._RealGetContents()g
  File "C:\Python39\lib\zipfile.py", line 1324, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

**Comment by YueChen-C** [comment]
Download the same version of DeviceSupport and put it in `%USERPROFILE%/.py_ios_device/device-support`
link:https://github.com/JinjunHan/iOSDeviceSupport/tree/master/DeviceSupport/

**Comment by popiggy** [comment]
thanks a lot, it works! the zip file was 32ko only instead of 11MB for the good one.... 
great job!
