### ISSUE TITLE
iOS 14.3 and up

### ISSUE THREAD

**Issue by Itaybre** [YueChen-C/py-ios-device#6]
I am having issues running this tool with iOS 14.3
Tried extracting the DeveloperDiskImage.dmg from Xcode.app but still fails

Is iOS 14.3 supported?
Here is the output (which doesn't make much sense to me since I can call the service from libimobiledevice):
```
2021-03-12 09:44:18,149 - lockdown.py[line:252] - INFO: ProductVersion: 14.3
2021-03-12 09:44:18,239 - image_mounter.py[line:75] - INFO: Pushing DeveloperDiskImage.dmg
2021-03-12 09:44:18,942 - image_mounter.py[line:88] - INFO: Push complete
2021-03-12 09:44:19,026 - lockdown.py[line:308] - INFO: DeveloperImage mounted successfully
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/ios_device/util/lockdown.py", line 312, in start_service
    return self._start_service(name, escrow_bag)
  File "/usr/local/lib/python3.9/site-packages/ios_device/util/lockdown.py", line 217, in _start_service
    raise StartServiceError(f'Unable to start service={name!r} - {error}')
ios_device.util.exceptions.StartServiceError: Unable to start service='com.apple.instruments.remoteserver.DVTSecureSocketProxy' - InvalidService

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/*****/*****/py-ios-device/demo/instrument_demo/sysmontap.py", line 52, in <module>
    rpc = InstrumentServer().init()
  File "/usr/local/lib/python3.9/site-packages/ios_device/servers/Instrument.py", line 30, in init
    raise E
  File "/usr/local/lib/python3.9/site-packages/ios_device/servers/Instrument.py", line 24, in init
    self._cli = self.lockdown.start_service("com.apple.instruments.remoteserver.DVTSecureSocketProxy")
  File "/usr/local/lib/python3.9/site-packages/ios_device/util/lockdown.py", line 316, in start_service
    return self._start_service(name, escrow_bag)
  File "/usr/local/lib/python3.9/site-packages/ios_device/util/lockdown.py", line 217, in _start_service
    raise StartServiceError(f'Unable to start service={name!r} - {error}')
ios_device.util.exceptions.StartServiceError: Unable to start service='com.apple.instruments.remoteserver.DVTSecureSocketProxy' - InvalidService
```

**Comment by Itaybre** [comment]
Seems like my device was failing to activate Development mode, after I restarted it, it is working
