### ISSUE TITLE
Still unable to use py-ios-device on m1 mac

### ISSUE THREAD

**Issue by kandji-joel** [YueChen-C/py-ios-device#72]
Follow-up from https://github.com/YueChen-C/py-ios-device/issues/69

I'm unable to use py-ios-device on m1 mac

```zsh
% pyidevice devices
Traceback (most recent call last):
  File "/Users/user/.pyenv/versions/3.9.10/bin/pyidevice", line 5, in <module>
    from ios_device.main import cli
  File "/Users/user/.pyenv/versions/3.9.10/lib/python3.9/site-packages/ios_device/main.py", line 2, in <module>
    from ios_device.cli.instruments import cli as instruments_cli
  File "/Users/user/.pyenv/versions/3.9.10/lib/python3.9/site-packages/ios_device/cli/instruments.py", line 12, in <module>
    from ios_device.cli.base import InstrumentsBase
  File "/Users/user/.pyenv/versions/3.9.10/lib/python3.9/site-packages/ios_device/cli/base.py", line 8, in <module>
    from ios_device.servers.Installation import InstallationProxyService
  File "/Users/user/.pyenv/versions/3.9.10/lib/python3.9/site-packages/ios_device/servers/Installation.py", line 29, in <module>
    from ..servers.afc import AFCClient
  File "/Users/user/.pyenv/versions/3.9.10/lib/python3.9/site-packages/ios_device/servers/afc.py", line 41, in <module>
    from ..util.lockdown import LockdownClient
  File "/Users/user/.pyenv/versions/3.9.10/lib/python3.9/site-packages/ios_device/util/lockdown.py", line 22, in <module>
    from .ca import make_certs_and_key
  File "/Users/user/.pyenv/versions/3.9.10/lib/python3.9/site-packages/ios_device/util/ca.py", line 5, in <module>
    from OpenSSL.crypto import X509, TYPE_RSA, X509Req, PKey, FILETYPE_PEM as PEM, X509Name, X509Extension
  File "/Users/user/.pyenv/versions/3.9.10/lib/python3.9/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/Users/user/.pyenv/versions/3.9.10/lib/python3.9/site-packages/OpenSSL/crypto.py", line 11, in <module>
    from OpenSSL._util import (
  File "/Users/user/.pyenv/versions/3.9.10/lib/python3.9/site-packages/OpenSSL/_util.py", line 5, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/Users/user/.pyenv/versions/3.9.10/lib/python3.9/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: dlopen(/Users/user/.pyenv/versions/3.9.10/lib/python3.9/site-packages/_cffi_backend.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace '_ffi_prep_closure'
```

I have tried the following suggestions with no luck. Has anyone else had any success?
- https://github.com/Kozea/cairocffi/issues/198#issuecomment-958102167
- https://foss.heptapod.net/pypy/cffi/-/issues/506
- https://foss.heptapod.net/pypy/cffi/-/issues/518
- https://stackoverflow.com/a/66055389

**Comment by kandji-joel** [comment]
Closing, could only reproduce on a specific machine
