### ISSUE TITLE
 命令：pyidevice instruments network_process -b com.tencent.xin    --udid 00008030-0001685034E8802E 不适用于14.7.1

### ISSUE THREAD

**Issue by hexiaolong-coco** [YueChen-C/py-ios-device#77]
cocos@cococsdeMacBook-Pro ~ % pyidevice instruments network_process -b com.tencent.xin --udid 00008030-0001685034E8802E
2022-10-20 14:46:52 [INFO] [LockDown] lockdown.py[line:73] Connecting Device 00008030-0001685034E8802E 
2022-10-20 14:46:52 [INFO] [Instrument] Instrument.py[line:22] InstrumentServer init ...
2022-10-20 14:46:52 [INFO] [LockDown] lockdown.py[line:73] Connecting Device 00008030-0001685034E8802E 
2022-10-20 14:46:52 [INFO] [LockDown] lockdown.py[line:302] ProductVersion: 14.7.1
2022-10-20 14:46:52 [INFO] [LockDown] lockdown.py[line:317] Download https://github.com/JinjunHan/iOSDeviceSupport/raw/master/DeviceSupport/14.7.zip -> /Users/cocos/.py_ios_device/device-support/14.7.zip
2022-10-20 14:46:52 [INFO] [LockDown] lockdown.py[line:280] Download https://raw.githubusercontent.com/filsv/iPhoneOSDeviceSupport/master/14.7.zip -> /Users/cocos/.py_ios_device/device-support/14.7.zip
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/ios_device/util/lockdown.py", line 350, in start_service
    return self._start_service(name, escrow_bag)
  File "/usr/local/lib/python3.9/site-packages/ios_device/util/lockdown.py", line 262, in _start_service
    raise StartServiceError(f'Unable to start service={name!r} - {error}')
ios_device.util.exceptions.StartServiceError: Unable to start service='com.apple.instruments.remoteserver.DVTSecureSocketProxy' - InvalidService

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x102a07370>: Failed to establish a new connection: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /filsv/iPhoneOSDeviceSupport/master/14.7.zip (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x102a07370>: Failed to establish a new connection: [Errno 61] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pyidevice", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/ios_device/main.py", line 10, in cli
    cli_commands()
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/ios_device/cli/instruments.py", line 138, in cmd_network_process
    pid = rpc.get_pid(bundle_id, name)
  File "/usr/local/lib/python3.9/site-packages/ios_device/cli/base.py", line 164, in get_pid
    app = self.application_listing(bundle_id)
  File "/usr/local/lib/python3.9/site-packages/ios_device/cli/base.py", line 231, in application_listing
    applist = self.instruments.call(InstrumentsService.ApplicationListing,
  File "/usr/local/lib/python3.9/site-packages/ios_device/cli/base.py", line 179, in instruments
    self.instruments_rcp = InstrumentServer(lockdown=self.lock_down).init()
  File "/usr/local/lib/python3.9/site-packages/ios_device/servers/Instrument.py", line 26, in init
    self._cli = self.lockdown.start_service("com.apple.instruments.remoteserver.DVTSecureSocketProxy")
  File "/usr/local/lib/python3.9/site-packages/ios_device/util/lockdown.py", line 352, in start_service
    self.mount_developer_image()
  File "/usr/local/lib/python3.9/site-packages/ios_device/util/lockdown.py", line 342, in mount_developer_image
    with self._request_developer_image_dir() as _dir:  # , signature_path:
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.9/site-packages/ios_device/util/lockdown.py", line 319, in _request_developer_image_dir
    self._urlretrieve(mirror_url, image_zip_path)
  File "/usr/local/lib/python3.9/site-packages/ios_device/util/lockdown.py", line 284, in _urlretrieve
    with requests.get(url, stream=True, timeout=DOWN_SUPPORT_TIMEOUT) as r:
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /filsv/iPhoneOSDeviceSupport/master/14.7.zip (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x102a07370>: Failed to establish a new connection: [Errno 61] Connection refused'))

**Comment by YueChen-C** [comment]
需要 14.7 镜像
