### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by Itaybre** [YueChen-C/py-ios-device#9]
I have managed to run this perfectly on MacOS, but I am having issues running it on Windows.
Every device I try to use fails when trying to connect to instruments service:

```
2021-04-05 00:52:09,671 - usbmux.py[line:275] - DEBUG: 发送 Plist: {'DeviceID': 11, 'PortNumber': 53958, 'ClientVersionString': 'apptim', 'MessageType': 'Connect', 'ProgName': 'tcprelay'}
2021-04-05 00:52:09,671 - usbmux.py[line:277] - DEBUG: 发送 Plist byte: b'<?xml version="1.0" encoding="UTF-8"?>\n<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n<plist version="1.0">\n<dict>\n\t<key>ClientVersionString</key>\n\t<string>apptim</string>\n\t<key>DeviceID</key>\n\t<integer>11</integer>\n\t<key>MessageType</key>\n\t<string>Connect</string>\n\t<key>PortNumber</key>\n\t<integer>53958</integer>\n\t<key>ProgName</key>\n\t<string>tcprelay</string>\n</dict>\n</plist>\n'
2021-04-05 00:52:09,671 - usbmux.py[line:282] - DEBUG: 接收 Plist byte: b'<?xml version="1.0" encoding="UTF-8"?>\n<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n<plist version="1.0">\n<dict>\n\t<key>MessageType</key>\n\t<string>Result</string>\n\t<key>Number</key>\n\t<integer>3</integer>\n</dict>\n</plist>\n'
2021-04-05 00:52:09,671 - usbmux.py[line:286] - DEBUG: 接收 Plist: {'MessageType': 'Result', 'Number': 3}
Traceback (most recent call last):
  File "C:\Users\***\ios_device\servers\Instrument.py", line 26, in init
    self._cli = self.lockdown.start_service("com.apple.instruments.remoteserver")
  File "C:\Users\***\ios_device\util\lockdown.py", line 312, in start_service
    return self._start_service(name, escrow_bag)
  File "C:\Users\***\ios_device\util\lockdown.py", line 219, in _start_service
    plist_service = PlistService(
  File "C:\Users\***\ios_device\util\plist_service.py", line 34, in __init__
    self.sock = self.device.connect(port)  # type: socket
  File "C:\Users\***\ios_device\util\usbmux.py", line 37, in connect
    return connector.connect(self, port)
  File "C:\Users\***\ios_device\util\usbmux.py", line 114, in connect
    raise MuxError('Connect failed: error %d' % ret)
ios_device.util.exceptions.MuxError: Connect failed: error 3
```

The code I run to get this is:
```python
device = PyiOSDevice(UDID)
print(device.get_capabilities())
device.stop()
```

The environment is Windows 10, with iTunes installed and libimobiledevice running fine.
Any idea what I am doing wrong? (I had to increase timeouts to be able to find the device)

**Comment by Itaybre** [comment]
Update: It seems that everything works fine if I open iTunes, but without it, I still get that error

**Comment by YueChen-C** [comment]
@Itaybre The iTunes "C:\Program Files\Common Files\Apple\Mobile Device Support\AppleMobileDeviceService.exe " driver is used by default on windows. Communicate with iOS by monitoring port 27105

**Comment by YueChen-C** [comment]
libimobiledevice uses [libimobiledevice/usbmuxd](https://github.com/libimobiledevice/usbmuxd)  to skip iTunes or other third-party software

**Comment by Itaybre** [comment]
Thanks for that, but any idea why it doesn't work without iTunes running?
I should start that driver manually from my app?

**Comment by Itaybre** [comment]
Mystery solved: I installed iTunes from the Windows Store, it doesn't seem to install AppleMobileDeviceService.exe
