### ISSUE TITLE
Sometimes we get no information about app lifecycle

### ISSUE THREAD

**Issue by sanidhya-saraswat** [YueChen-C/py-ios-device#92]
_Installed using pip, tool version: 2.3.21_

Please refer to below screenshot:

<img width="1071" alt="Screenshot 2023-02-24 at 3 31 19 PM" src="https://user-images.githubusercontent.com/21276981/221150909-b635647a-86ec-485f-9261-fadb99aa35b4.png">

**Comment by sanidhya-saraswat** [comment]
One more similar issue:

 While running `demo/app_lifecycle.py` on the latest code, getting this error:

This issue also comes while using the pip module.
 
```~/repos/py-ios-device  main !1  python3 demo/instrument_demo/app_lifecycle.py
2023-02-24 15:42:06 [INFO] [LockDown] lockdown.py[line:73] Connecting Device xxxxxx-xxxxxxxx
2023-02-24 15:42:06 [INFO] [Instrument] Instrument.py[line:22] InstrumentServer init ...
2023-02-24 15:42:06 [INFO] [Instrument] dvt.py[line:167] set com.apple.instruments.server.services.coreprofilesessiontap callback ...
2023-02-24 15:42:06 [INFO] [LockDown] lockdown.py[line:73] Connecting Device xxxxx-xxxxxxx 
2023-02-24 15:42:06 [INFO] [Instrument] Instrument.py[line:22] InstrumentServer init ...
2023-02-24 15:42:06 [ERROR] [Instrument] dvt.py[line:252] could not find container end marker
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/ios_device/servers/dvt.py", line 239, in _receiver
    self._channel_callbacks[(2 ** 32 - dtx.channel_code)](dtx)
  File "/Users/sanidhya/repos/py-ios-device/demo/instrument_demo/app_lifecycle.py", line 32, in on_graphics_message
    demo(res.selector.data)
  File "/Users/sanidhya/repos/py-ios-device/demo/instrument_demo/app_lifecycle.py", line 22, in demo
    for event in Kperf.to_dict(data):
  File "/opt/homebrew/lib/python3.9/site-packages/ios_device/util/kperf_data.py", line 1021, in to_dict
    for event in self.parse(kd_buf):
  File "/opt/homebrew/lib/python3.9/site-packages/ios_device/util/kperf_data.py", line 971, in parse
    yield kc_data_parse(buf_io.read())
  File "/opt/homebrew/lib/python3.9/site-packages/ios_device/util/kc_data.py", line 1710, in kc_data_parse
    for i, kcdata_buffer in enumerate(iterate_kcdatas(data)):
  File "/opt/homebrew/lib/python3.9/site-packages/ios_device/util/kc_data.py", line 1667, in iterate_kcdatas
    kcdata_buffer.ReadItems(iterator)
  File "/opt/homebrew/lib/python3.9/site-packages/ios_device/util/kc_data.py", line 670, in ReadItems
    o.ReadItems(iterator)
  File "/opt/homebrew/lib/python3.9/site-packages/ios_device/util/kc_data.py", line 670, in ReadItems
    o.ReadItems(iterator)
  File "/opt/homebrew/lib/python3.9/site-packages/ios_device/util/kc_data.py", line 677, in ReadItems
    raise Exception(self.no_end_message)
Exception: could not find container end marker
start notion.id pid:22491```

**Comment by YueChen-C** [comment]
This issue has been fixed https://github.com/YueChen-C/py-ios-device/commit/c5e64d1550d69a4b8a2e9306c07e50fe013c68a3 , and 2.3.22 will be released today
